# Generated by Django 3.2.4 on 2021-06-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
